---
title: "Fit the Continuous-Time Vector Autoregressive Model Using the OpenMx Package"
author: Ivan Jacob Agaloos Pesigan
date: "2025-02-11"
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @RCoreTeam-2024
  @Neale-Hunter-Pritikin-etal-2015
  @Hunter-2017
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fit the Continuous-Time Vector Autoregressive Model Using the OpenMx Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---





## Data Generation Using the `SimSSMOUFixed` Function from the `simStateSpace` Package


``` r
n
#> [1] 50
time
#> [1] 100
delta_t
#> [1] 0.1
mu0
#> [1] 0 0 0
sigma0
#>      [,1] [,2] [,3]
#> [1,]  1.0  0.2  0.2
#> [2,]  0.2  1.0  0.2
#> [3,]  0.2  0.2  1.0
sigma0_l # sigma0_l <- t(chol(sigma0))
#>      [,1]      [,2]      [,3]
#> [1,]  1.0 0.0000000 0.0000000
#> [2,]  0.2 0.9797959 0.0000000
#> [3,]  0.2 0.1632993 0.9660918
mu
#> [1] 0 0 0
phi
#>        [,1]   [,2]   [,3]
#> [1,] -0.357  0.000  0.000
#> [2,]  0.771 -0.511  0.000
#> [3,] -0.450  0.729 -0.693
sigma
#>             [,1]       [,2]        [,3]
#> [1,]  0.24455556 0.02201587 -0.05004762
#> [2,]  0.02201587 0.07067800  0.01539456
#> [3,] -0.05004762 0.01539456  0.07553061
sigma_l # sigma_l <- t(chol(sigma))
#>             [,1]      [,2]     [,3]
#> [1,]  0.49452559 0.0000000 0.000000
#> [2,]  0.04451917 0.2620993 0.000000
#> [3,] -0.10120330 0.0759256 0.243975
nu
#> [1] 0 0 0
lambda
#>      [,1] [,2] [,3]
#> [1,]    1    0    0
#> [2,]    0    1    0
#> [3,]    0    0    1
theta
#>      [,1] [,2] [,3]
#> [1,]  0.2  0.0  0.0
#> [2,]  0.0  0.2  0.0
#> [3,]  0.0  0.0  0.2
theta_l # theta_l <- t(chol(theta))
#>           [,1]      [,2]      [,3]
#> [1,] 0.4472136 0.0000000 0.0000000
#> [2,] 0.0000000 0.4472136 0.0000000
#> [3,] 0.0000000 0.0000000 0.4472136
```


``` r
library(simStateSpace)
sim <- SimSSMOUFixed(
  n = n,
  time = time,
  delta_t = delta_t,
  mu0 = mu0,
  sigma0_l = sigma0_l,
  mu = mu,
  phi = phi,
  sigma_l = sigma_l,
  nu = nu,
  lambda = lambda,
  theta_l = theta_l,
  type = 0
)
data <- as.data.frame(sim)
colnames(data) <- c("id", "time", "x", "m", "y")
head(data)
#>   id time          x          m        y
#> 1  1  0.0 -0.3504435 0.41877429 2.611996
#> 2  1  0.1 -0.5920330 1.07433208 1.669272
#> 3  1  0.2 -0.7619855 1.21483834 2.369837
#> 4  1  0.3 -1.6964652 0.21209722 2.128531
#> 5  1  0.4 -1.2282686 0.09950326 1.891140
#> 6  1  0.5  0.1433985 0.66784226 2.036033
```

## Model Fitting

We use the `OpenMx` package to fit the continuous-time vector autoregressive model.




``` r
library(OpenMx)
```

### Prepare the Initial Condition


``` r
mu0 <- mxMatrix(
  type = "Full",
  nrow = 3,
  ncol = 1,
  free = TRUE,
  values = matrix(
    data = c(
      0, 0, 0
    ),
    nrow = 3,
    ncol = 1
  ),
  labels = matrix(
    data = c(
      "mu0_1_1", "mu0_2_1", "mu0_3_1"
    ),
    nrow = 3,
    ncol = 1
  ),
  lbound = NA,
  ubound = NA,
  byrow = FALSE,
  dimnames = list(
    c("eta_x", "eta_m", "eta_y"),
    "mu0"
  ),
  name = "mu0"
)
sigma0 <- mxMatrix(
  type = "Symm",
  nrow = 3,
  ncol = 3,
  free = TRUE,
  values = matrix(
    data = c(
      1.0, 0.2, 0.2,
      0.2, 1.0, 0.2,
      0.2, 0.2, 1.0
    ),
    nrow = 3,
    ncol = 3
  ),
  labels = matrix(
    data = c(
      "sigma0_1_1", "sigma0_2_1", "sigma0_3_1",
      "sigma0_2_1", "sigma0_2_2", "sigma0_3_2",
      "sigma0_3_1", "sigma0_3_2", "sigma0_3_3"
    ),
    nrow = 3,
    ncol = 3
  ),
  lbound = matrix(
    data = c(
      0, NA, NA,
      NA, 0, NA,
      NA, NA, 0
    ),
    nrow = 3,
    ncol = 3
  ),
  ubound = NA,
  byrow = FALSE,
  dimnames = list(
    c("eta_x", "eta_m", "eta_y"),
    c("eta_x", "eta_m", "eta_y")
  ),
  name = "sigma0"
)
```

### Prepare the Measurement Model


``` r
lambda <- mxMatrix(
  type = "Diag",
  nrow = 3,
  ncol = 3,
  free = FALSE,
  values = 1,
  labels = NA,
  lbound = NA,
  ubound = NA,
  byrow = FALSE,
  dimnames = list(
    c("x", "m", "y"),
    c("eta_x", "eta_m", "eta_y")
  ),
  name = "lambda"
)
```

### Prepare the Dynamic Model


``` r
phi <- mxMatrix(
  type = "Full",
  nrow = 3,
  ncol = 3,
  free = TRUE,
  values = matrix(
    data = c(
      -0.2, 0.0, 0.0,
      0.0, -0.2, 0.0,
      0.0, 0.0, -0.2
    ),
    nrow = 3,
    ncol = 3
  ),
  labels = matrix(
    data = c(
      "phi_1_1", "phi_2_1", "phi_3_1",
      "phi_1_2", "phi_2_2", "phi_3_2",
      "phi_1_3", "phi_2_3", "phi_3_3"
    ),
    nrow = 3,
    ncol = 3
  ),
  lbound = -1.5,
  ubound = 1.5,
  byrow = FALSE,
  dimnames = list(
    c("eta_x", "eta_m", "eta_y"),
    c("eta_x", "eta_m", "eta_y")
  ),
  name = "phi"
)
```

### Prepare the Noise Matrices


``` r
sigma <- mxMatrix(
  type = "Symm",
  nrow = 3,
  ncol = 3,
  free = TRUE,
  values = 0.2 * diag(3),
  labels = matrix(
    data = c(
      "sigma_1_1", "sigma_2_1", "sigma_3_1",
      "sigma_2_1", "sigma_2_2", "sigma_3_2",
      "sigma_3_1", "sigma_3_2", "sigma_3_3"
    ),
    nrow = 3,
    ncol = 3
  ),
  lbound = matrix(
    data = c(
      0, NA, NA,
      NA, 0, NA,
      NA, NA, 0
    ),
    nrow = 3,
    ncol = 3
  ),
  ubound = NA,
  byrow = FALSE,
  dimnames = list(
    c("eta_x", "eta_m", "eta_y"),
    c("eta_x", "eta_m", "eta_y")
  ),
  name = "sigma"
)
theta <- mxMatrix(
  type = "Diag",
  nrow = 3,
  ncol = 3,
  free = TRUE,
  values = 0.2 * diag(3),
  labels = matrix(
    data = c(
      "theta_1_1", "fixed", "fixed",
      "fixed", "theta_2_2", "fixed",
      "fixed", "fixed", "theta_3_3"
    ),
    nrow = 3,
    ncol = 3
  ),
  lbound = matrix(
    data = c(
      0, NA, NA,
      NA, 0, NA,
      NA, NA, 0
    ),
    nrow = 3,
    ncol = 3
  ),
  ubound = NA,
  byrow = FALSE,
  dimnames = list(
    c("x", "m", "y"),
    c("x", "m", "y")
  ),
  name = "theta"
)
```

### Prepare Miscellaneous Matrices


``` r
time <- mxMatrix(
  type = "Full",
  nrow = 1,
  ncol = 1,
  free = FALSE,
  labels = "data.time",
  name = "time"
)
gamma <- mxMatrix(
  type = "Zero",
  nrow = 3,
  ncol = 1,
  name = "gamma"
)
kappa <- mxMatrix(
  type = "Zero",
  nrow = 3,
  ncol = 1,
  name = "kappa"
)
covariate <- mxMatrix(
  type = "Zero",
  nrow = 1,
  ncol = 1,
  name = "covariate"
)
```

### Prepare the Model

In this parameterization, we fit the same model to all individuals (`id`) using a multi-group framework, assuming that the parameters remain fixed across individuals.


``` r
model <- mxModel(
  model = "CTVAR",
  phi,
  gamma,
  lambda,
  kappa,
  sigma,
  theta,
  mu0,
  sigma0,
  covariate,
  time,
  mxExpectationStateSpaceContinuousTime(
    A = "phi",
    B = "gamma",
    C = "lambda",
    D = "kappa",
    Q = "sigma",
    R = "theta",
    x0 = "mu0",
    P0 = "sigma0",
    u = "covariate",
    t = "time",
    dimnames = c("x", "m", "y")
  ),
  mxFitFunctionML(),
  mxData(
    observed = data,
    type = "raw"
  )
)
ids <- sort(
  unique(data[, "id"])
)
model_id <- lapply(
  X = ids,
  FUN = function(i,
                 data,
                 model) {
    return(
      mxModel(
        name = paste0("CTVAR", "_", i),
        model = model,
        mxData(
          observed = data[
            which(
              data[, "id"] == i
            ), ,
            drop = FALSE
          ],
          type = "raw"
        )
      )
    )
  },
  data = data,
  model = model
)
```

### Fit the Model


``` r
fit <- mxTryHardctsem(
  model = mxModel(
    name = "CTVAR",
    model_id,
    mxFitFunctionMultigroup(
      paste0(
        "CTVAR",
        "_",
        ids
      )
    )
  ),
  extraTries = 1000
)
#> Running CTVAR with 27 parameters
#> 
#> Beginning initial fit attempt
#> Running CTVAR with 27 parameters
#> 
#>  Lowest minimum so far:  21626.5696149473
#> 
#> Solution found
```



```
#> 
#>  Solution found!  Final fit=21626.57 (started at 22577.553)  (1 attempt(s): 1 valid, 0 errors)
#>  Start values from best fit:
#> -0.29379097710247,0.824373596871192,-0.454352941158215,-0.0719257338262605,-0.568941561045426,0.707694576680455,0.0257889220918782,0.0826903187980482,-0.687497461423581,0.23016000976406,0.0279936281650791,0.0788922446527097,-0.0678961701647397,0.00451046219167851,0.0843652758341329,0.201040220843954,0.191651067953274,0.197460049245072,-0.0684443090318708,0.084620014481904,0.11577024165373,0.942751957746392,0.161848192692847,1.48976467331756,0.103298443374234,-0.100426749650912,0.946206274665807
summary(fit)
#> Summary of CTVAR 
#>  
#> free parameters:
#>          name         matrix   row   col     Estimate   Std.Error A lbound
#> 1     phi_1_1    CTVAR_1.phi eta_x eta_x -0.293790977 0.082166191     -1.5
#> 2     phi_2_1    CTVAR_1.phi eta_m eta_x  0.824373597 0.056724536     -1.5
#> 3     phi_3_1    CTVAR_1.phi eta_y eta_x -0.454352941 0.057718856     -1.5
#> 4     phi_1_2    CTVAR_1.phi eta_x eta_m -0.071925734 0.068489344     -1.5
#> 5     phi_2_2    CTVAR_1.phi eta_m eta_m -0.568941561 0.048337545     -1.5
#> 6     phi_3_2    CTVAR_1.phi eta_y eta_m  0.707694577 0.048686321     -1.5
#> 7     phi_1_3    CTVAR_1.phi eta_x eta_y  0.025788922 0.062394707     -1.5
#> 8     phi_2_3    CTVAR_1.phi eta_m eta_y  0.082690319 0.043352142     -1.5
#> 9     phi_3_3    CTVAR_1.phi eta_y eta_y -0.687497461 0.044110977     -1.5
#> 10  sigma_1_1  CTVAR_1.sigma eta_x eta_x  0.230160010 0.022633005        0
#> 11  sigma_2_1  CTVAR_1.sigma eta_x eta_m  0.027993628 0.009999833         
#> 12  sigma_2_2  CTVAR_1.sigma eta_m eta_m  0.078892245 0.009570754        0
#> 13  sigma_3_1  CTVAR_1.sigma eta_x eta_y -0.067896170 0.010706969         
#> 14  sigma_3_2  CTVAR_1.sigma eta_m eta_y  0.004510462 0.006768996         
#> 15  sigma_3_3  CTVAR_1.sigma eta_y eta_y  0.084365276 0.010385774        0
#> 16  theta_1_1  CTVAR_1.theta     x     x  0.201040221 0.005103870        0
#> 17  theta_2_2  CTVAR_1.theta     m     m  0.191651068 0.004371699        0
#> 18  theta_3_3  CTVAR_1.theta     y     y  0.197460049 0.004520320        0
#> 19    mu0_1_1    CTVAR_1.mu0 eta_x   mu0 -0.068444309 0.141891679         
#> 20    mu0_2_1    CTVAR_1.mu0 eta_m   mu0  0.084620014 0.175331130         
#> 21    mu0_3_1    CTVAR_1.mu0 eta_y   mu0  0.115770242 0.141163223         
#> 22 sigma0_1_1 CTVAR_1.sigma0 eta_x eta_x  0.942751958 0.202360338        0
#> 23 sigma0_2_1 CTVAR_1.sigma0 eta_x eta_m  0.161848193 0.178510099         
#> 24 sigma0_2_2 CTVAR_1.sigma0 eta_m eta_m  1.489764673 0.309901840        0
#> 25 sigma0_3_1 CTVAR_1.sigma0 eta_x eta_y  0.103298443 0.143316923 !       
#> 26 sigma0_3_2 CTVAR_1.sigma0 eta_m eta_y -0.100426750 0.177066649 !       
#> 27 sigma0_3_3 CTVAR_1.sigma0 eta_y eta_y  0.946206275 0.201133302 !      0
#>    ubound
#> 1     1.5
#> 2     1.5
#> 3     1.5
#> 4     1.5
#> 5     1.5
#> 6     1.5
#> 7     1.5
#> 8     1.5
#> 9     1.5
#> 10       
#> 11       
#> 12       
#> 13       
#> 14       
#> 15       
#> 16       
#> 17       
#> 18       
#> 19       
#> 20       
#> 21       
#> 22       
#> 23       
#> 24       
#> 25       
#> 26       
#> 27       
#> 
#> Model Statistics: 
#>                |  Parameters  |  Degrees of Freedom  |  Fit (-2lnL units)
#>        Model:             27                  14973              21626.57
#>    Saturated:             NA                     NA                    NA
#> Independence:             NA                     NA                    NA
#> Number of observations/statistics: 5000/15000
#> 
#> Information Criteria: 
#>       |  df Penalty  |  Parameters Penalty  |  Sample-Size Adjusted
#> AIC:       -8319.43               21680.57                 21680.87
#> BIC:     -105901.36               21856.53                 21770.74
#> CFI: NA 
#> TLI: 1   (also known as NNFI) 
#> RMSEA:  0  [95% CI (NA, NA)]
#> Prob(RMSEA <= 0.05): NA
#> To get additional fit indices, see help(mxRefModels)
#> timestamp: 2025-02-11 06:31:07 
#> Wall clock time: 236.0198 secs 
#> optimizer:  SLSQP 
#> OpenMx version number: 2.21.13 
#> Need help?  See help(mxSummary)
coefs <- coef(fit)
vcovs <- vcov(fit)
```

### Extract Matrices from the Fitted Model to use in cTMed


``` r
phi_names <- c(
  "phi_1_1", "phi_2_1", "phi_3_1",
  "phi_1_2", "phi_2_2", "phi_3_2",
  "phi_1_3", "phi_2_3", "phi_3_3"
)
sigma_names <- c(
  "sigma_1_1", "sigma_2_1", "sigma_3_1",
  "sigma_2_1", "sigma_2_2", "sigma_3_2",
  "sigma_3_1", "sigma_3_2", "sigma_3_3"
)
sigma_vech_names <- c(
  "sigma_1_1", "sigma_2_1", "sigma_3_1",
  "sigma_2_2", "sigma_3_2",
  "sigma_3_3"
)
theta_names <- c(
  "phi_1_1", "phi_2_1", "phi_3_1",
  "phi_1_2", "phi_2_2", "phi_3_2",
  "phi_1_3", "phi_2_3", "phi_3_3",
  "sigma_1_1", "sigma_2_1", "sigma_3_1",
  "sigma_2_2", "sigma_3_2",
  "sigma_3_3"
)
phi <- matrix(
  data = coefs[phi_names],
  nrow = 3,
  ncol = 3
)
sigma <- matrix(
  data = coefs[sigma_names],
  nrow = 3,
  ncol = 3
)
theta <- coefs[theta_names]
vcov_phi_vec <- vcovs[phi_names, phi_names]
vcov_sigma_vech <- vcovs[sigma_vech_names, sigma_vech_names]
vcov_theta <- vcovs[theta_names, theta_names]
```

#### Estimated Drift Matrix with Corresponding Sampling Covariance Matrix


``` r
phi
#>            [,1]        [,2]        [,3]
#> [1,] -0.2937910 -0.07192573  0.02578892
#> [2,]  0.8243736 -0.56894156  0.08269032
#> [3,] -0.4543529  0.70769458 -0.68749746
vcov_phi_vec
#>               phi_1_1       phi_2_1       phi_3_1       phi_1_2       phi_2_2
#> phi_1_1  0.0067512830  3.309225e-04 -0.0014381281 -0.0048573303 -2.760613e-04
#> phi_2_1  0.0003309225  3.217673e-03 -0.0001191910 -0.0001299004 -2.405236e-03
#> phi_3_1 -0.0014381281 -1.191910e-04  0.0033314663  0.0009794905  1.083118e-04
#> phi_1_2 -0.0048573303 -1.299004e-04  0.0009794905  0.0046907902  1.917779e-04
#> phi_2_2 -0.0002760613 -2.405236e-03  0.0001083118  0.0001917779  2.336518e-03
#> phi_3_2  0.0010368200  3.920789e-05 -0.0024546076 -0.0009978418 -8.257311e-05
#> phi_1_3  0.0033229607  4.862890e-05 -0.0006133403 -0.0033986894 -8.625553e-05
#> phi_2_3  0.0002236731  1.674431e-03 -0.0001010005 -0.0001915267 -1.715274e-03
#> phi_3_3 -0.0007334162 -8.023179e-06  0.0016918283  0.0007505617  3.134592e-05
#>               phi_3_2       phi_1_3       phi_2_3       phi_3_3
#> phi_1_1  1.036820e-03  3.322961e-03  2.236731e-04 -7.334162e-04
#> phi_2_1  3.920789e-05  4.862890e-05  1.674431e-03 -8.023179e-06
#> phi_3_1 -2.454608e-03 -6.133403e-04 -1.010005e-04  1.691828e-03
#> phi_1_2 -9.978418e-04 -3.398689e-03 -1.915267e-04  7.505617e-04
#> phi_2_2 -8.257311e-05 -8.625553e-05 -1.715274e-03  3.134592e-05
#> phi_3_2  2.370358e-03  6.709785e-04  1.031267e-04 -1.736972e-03
#> phi_1_3  6.709785e-04  3.893099e-03  1.804313e-04 -8.706979e-04
#> phi_2_3  1.031267e-04  1.804313e-04  1.879408e-03 -9.776183e-05
#> phi_3_3 -1.736972e-03 -8.706979e-04 -9.776183e-05  1.945778e-03
```

#### Process Noise Covariance Matrix with Corresponding Sampling Covariance Matrix


``` r
sigma
#>             [,1]        [,2]         [,3]
#> [1,]  0.23016001 0.027993628 -0.067896170
#> [2,]  0.02799363 0.078892245  0.004510462
#> [3,] -0.06789617 0.004510462  0.084365276
vcov_sigma_vech
#>               sigma_1_1     sigma_2_1     sigma_3_1     sigma_2_2     sigma_3_2
#> sigma_1_1  5.122529e-04  2.210556e-05 -9.555142e-05  6.993021e-07 -4.525693e-06
#> sigma_2_1  2.210556e-05  9.999665e-05 -7.120332e-06  1.111274e-05 -2.361914e-05
#> sigma_3_1 -9.555142e-05 -7.120332e-06  1.146392e-04 -1.027202e-06  7.394396e-06
#> sigma_2_2  6.993021e-07  1.111274e-05 -1.027202e-06  9.159933e-05 -5.224141e-06
#> sigma_3_2 -4.525693e-06 -2.361914e-05  7.394396e-06 -5.224141e-06  4.581931e-05
#> sigma_3_3  1.719246e-05  3.462719e-06 -4.884374e-05  1.149757e-08 -5.945249e-06
#>               sigma_3_3
#> sigma_1_1  1.719246e-05
#> sigma_2_1  3.462719e-06
#> sigma_3_1 -4.884374e-05
#> sigma_2_2  1.149757e-08
#> sigma_3_2 -5.945249e-06
#> sigma_3_3  1.078643e-04
```

#### Estimated Drift Matrix and Process Noise Covariance Matrix with Corresponding Sampling Covariance Matrix


``` r
theta
#>      phi_1_1      phi_2_1      phi_3_1      phi_1_2      phi_2_2      phi_3_2 
#> -0.293790977  0.824373597 -0.454352941 -0.071925734 -0.568941561  0.707694577 
#>      phi_1_3      phi_2_3      phi_3_3    sigma_1_1    sigma_2_1    sigma_3_1 
#>  0.025788922  0.082690319 -0.687497461  0.230160010  0.027993628 -0.067896170 
#>    sigma_2_2    sigma_3_2    sigma_3_3 
#>  0.078892245  0.004510462  0.084365276
vcov_theta
#>                 phi_1_1       phi_2_1       phi_3_1       phi_1_2       phi_2_2
#> phi_1_1    6.751283e-03  3.309225e-04 -1.438128e-03 -4.857330e-03 -2.760613e-04
#> phi_2_1    3.309225e-04  3.217673e-03 -1.191910e-04 -1.299004e-04 -2.405236e-03
#> phi_3_1   -1.438128e-03 -1.191910e-04  3.331466e-03  9.794905e-04  1.083118e-04
#> phi_1_2   -4.857330e-03 -1.299004e-04  9.794905e-04  4.690790e-03  1.917779e-04
#> phi_2_2   -2.760613e-04 -2.405236e-03  1.083118e-04  1.917779e-04  2.336518e-03
#> phi_3_2    1.036820e-03  3.920789e-05 -2.454608e-03 -9.978418e-04 -8.257311e-05
#> phi_1_3    3.322961e-03  4.862890e-05 -6.133403e-04 -3.398689e-03 -8.625553e-05
#> phi_2_3    2.236731e-04  1.674431e-03 -1.010005e-04 -1.915267e-04 -1.715274e-03
#> phi_3_3   -7.334162e-04 -8.023179e-06  1.691828e-03  7.505617e-04  3.134592e-05
#> sigma_1_1 -1.136847e-03 -1.287062e-04  2.706512e-04  6.652561e-04  7.825909e-05
#> sigma_2_1  9.497544e-05 -2.296141e-04 -3.698837e-05 -1.409965e-04  1.216216e-04
#> sigma_3_1  1.232748e-04  1.950668e-05 -2.547148e-04 -1.954526e-05 -4.270096e-06
#> sigma_2_2  1.506877e-05  1.014180e-04  5.251615e-06 -1.691801e-05 -1.366091e-04
#> sigma_3_2 -2.441758e-05  2.731562e-05  5.102487e-05  3.503303e-05  9.128860e-06
#> sigma_3_3 -1.819907e-06 -1.298757e-05  4.432849e-05 -2.036510e-05  5.781343e-06
#>                 phi_3_2       phi_1_3       phi_2_3       phi_3_3     sigma_1_1
#> phi_1_1    1.036820e-03  3.322961e-03  2.236731e-04 -7.334162e-04 -1.136847e-03
#> phi_2_1    3.920789e-05  4.862890e-05  1.674431e-03 -8.023179e-06 -1.287062e-04
#> phi_3_1   -2.454608e-03 -6.133403e-04 -1.010005e-04  1.691828e-03  2.706512e-04
#> phi_1_2   -9.978418e-04 -3.398689e-03 -1.915267e-04  7.505617e-04  6.652561e-04
#> phi_2_2   -8.257311e-05 -8.625553e-05 -1.715274e-03  3.134592e-05  7.825909e-05
#> phi_3_2    2.370358e-03  6.709785e-04  1.031267e-04 -1.736972e-03 -1.637531e-04
#> phi_1_3    6.709785e-04  3.893099e-03  1.804313e-04 -8.706979e-04 -3.382067e-04
#> phi_2_3    1.031267e-04  1.804313e-04  1.879408e-03 -9.776183e-05 -4.355874e-05
#> phi_3_3   -1.736972e-03 -8.706979e-04 -9.776183e-05  1.945778e-03  8.980916e-05
#> sigma_1_1 -1.637531e-04 -3.382067e-04 -4.355874e-05  8.980916e-05  5.122529e-04
#> sigma_2_1  4.521435e-05  9.557236e-05 -5.431899e-05 -3.060797e-05  2.210556e-05
#> sigma_3_1  1.294992e-04 -9.282355e-05 -1.105522e-05 -3.083702e-05 -9.555142e-05
#> sigma_2_2 -5.206801e-06  1.205693e-05  8.854417e-05  3.289020e-06  6.993021e-07
#> sigma_3_2 -6.831112e-05 -2.749640e-05 -4.766928e-05  4.405685e-05 -4.525693e-06
#> sigma_3_3  2.872058e-05  5.375442e-05  4.378105e-06 -1.164000e-04  1.719246e-05
#>               sigma_2_1     sigma_3_1     sigma_2_2     sigma_3_2     sigma_3_3
#> phi_1_1    9.497544e-05  1.232748e-04  1.506877e-05 -2.441758e-05 -1.819907e-06
#> phi_2_1   -2.296141e-04  1.950668e-05  1.014180e-04  2.731562e-05 -1.298757e-05
#> phi_3_1   -3.698837e-05 -2.547148e-04  5.251615e-06  5.102487e-05  4.432849e-05
#> phi_1_2   -1.409965e-04 -1.954526e-05 -1.691801e-05  3.503303e-05 -2.036510e-05
#> phi_2_2    1.216216e-04 -4.270096e-06 -1.366091e-04  9.128860e-06  5.781343e-06
#> phi_3_2    4.521435e-05  1.294992e-04 -5.206801e-06 -6.831112e-05  2.872058e-05
#> phi_1_3    9.557236e-05 -9.282355e-05  1.205693e-05 -2.749640e-05  5.375442e-05
#> phi_2_3   -5.431899e-05 -1.105522e-05  8.854417e-05 -4.766928e-05  4.378105e-06
#> phi_3_3   -3.060797e-05 -3.083702e-05  3.289020e-06  4.405685e-05 -1.164000e-04
#> sigma_1_1  2.210556e-05 -9.555142e-05  6.993021e-07 -4.525693e-06  1.719246e-05
#> sigma_2_1  9.999665e-05 -7.120332e-06  1.111274e-05 -2.361914e-05  3.462719e-06
#> sigma_3_1 -7.120332e-06  1.146392e-04 -1.027202e-06  7.394396e-06 -4.884374e-05
#> sigma_2_2  1.111274e-05 -1.027202e-06  9.159933e-05 -5.224141e-06  1.149757e-08
#> sigma_3_2 -2.361914e-05  7.394396e-06 -5.224141e-06  4.581931e-05 -5.945249e-06
#> sigma_3_3  3.462719e-06 -4.884374e-05  1.149757e-08 -5.945249e-06  1.078643e-04
```

## References


