---
title: "Fit the Continuous-Time Vector Autoregressive Model Using the dynr Package"
author: Ivan Jacob Agaloos Pesigan
date: "2025-02-11"
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @RCoreTeam-2024
  @Ou-Hunter-Chow-2019
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fit the Continuous-Time Vector Autoregressive Model Using the dynr Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---





## Data Generation Using the `SimSSMOUFixed` Function from the `simStateSpace` Package


``` r
n
#> [1] 50
time
#> [1] 100
delta_t
#> [1] 0.1
mu0
#> [1] 0 0 0
sigma0
#>      [,1] [,2] [,3]
#> [1,]  1.0  0.2  0.2
#> [2,]  0.2  1.0  0.2
#> [3,]  0.2  0.2  1.0
sigma0_l # sigma0_l <- t(chol(sigma0))
#>      [,1]      [,2]      [,3]
#> [1,]  1.0 0.0000000 0.0000000
#> [2,]  0.2 0.9797959 0.0000000
#> [3,]  0.2 0.1632993 0.9660918
mu
#> [1] 0 0 0
phi
#>        [,1]   [,2]   [,3]
#> [1,] -0.357  0.000  0.000
#> [2,]  0.771 -0.511  0.000
#> [3,] -0.450  0.729 -0.693
sigma
#>             [,1]       [,2]        [,3]
#> [1,]  0.24455556 0.02201587 -0.05004762
#> [2,]  0.02201587 0.07067800  0.01539456
#> [3,] -0.05004762 0.01539456  0.07553061
sigma_l # sigma_l <- t(chol(sigma))
#>             [,1]      [,2]     [,3]
#> [1,]  0.49452559 0.0000000 0.000000
#> [2,]  0.04451917 0.2620993 0.000000
#> [3,] -0.10120330 0.0759256 0.243975
nu
#> [1] 0 0 0
lambda
#>      [,1] [,2] [,3]
#> [1,]    1    0    0
#> [2,]    0    1    0
#> [3,]    0    0    1
theta
#>      [,1] [,2] [,3]
#> [1,]  0.2  0.0  0.0
#> [2,]  0.0  0.2  0.0
#> [3,]  0.0  0.0  0.2
theta_l # theta_l <- t(chol(theta))
#>           [,1]      [,2]      [,3]
#> [1,] 0.4472136 0.0000000 0.0000000
#> [2,] 0.0000000 0.4472136 0.0000000
#> [3,] 0.0000000 0.0000000 0.4472136
```


``` r
library(simStateSpace)
sim <- SimSSMOUFixed(
  n = n,
  time = time,
  delta_t = delta_t,
  mu0 = mu0,
  sigma0_l = sigma0_l,
  mu = mu,
  phi = phi,
  sigma_l = sigma_l,
  nu = nu,
  lambda = lambda,
  theta_l = theta_l,
  type = 0
)
data <- as.data.frame(sim)
colnames(data) <- c("id", "time", "x", "m", "y")
head(data)
#>   id time          x          m        y
#> 1  1  0.0 -0.3504435 0.41877429 2.611996
#> 2  1  0.1 -0.5920330 1.07433208 1.669272
#> 3  1  0.2 -0.7619855 1.21483834 2.369837
#> 4  1  0.3 -1.6964652 0.21209722 2.128531
#> 5  1  0.4 -1.2282686 0.09950326 1.891140
#> 6  1  0.5  0.1433985 0.66784226 2.036033
```

## Model Fitting

We use the `dynr` package to fit the continuous-time vector autoregressive model.




``` r
library(dynr)
```

### Prepare the Data


``` r
dynr_data <- dynr.data(
  dataframe = data,
  id = "id",
  time = "time",
  observed = c("x", "m", "y")
)
```

### Prepare the Initial Condition


``` r
dynr_initial <- prep.initial(
  values.inistate = c(
    0, 0, 0
  ),
  params.inistate = c(
    "mu0_1_1", "mu0_2_1", "mu0_3_1"
  ),
  values.inicov = matrix(
    data = c(
      1.0, 0.2, 0.2,
      0.2, 1.0, 0.2,
      0.2, 0.2, 1.0
    ),
    nrow = 3
  ),
  params.inicov = matrix(
    data = c(
      "sigma0_1_1", "sigma0_2_1", "sigma0_3_1",
      "sigma0_2_1", "sigma0_2_2", "sigma0_3_2",
      "sigma0_3_1", "sigma0_3_2", "sigma0_3_3"
    ),
    nrow = 3
  )
)
```

### Prepare the Measurement Model


``` r
dynr_measurement <- prep.measurement(
  values.load = diag(3),
  params.load = matrix(
    data = "fixed",
    nrow = 3,
    ncol = 3
  ),
  state.names = c("eta_x", "eta_m", "eta_y"),
  obs.names = c("x", "m", "y")
)
```

### Prepare the Dynamic Model


``` r
dynr_dynamics <- prep.formulaDynamics(
  formula = list(
    eta_x ~ phi_1_1 * eta_x + phi_1_2 * eta_m + phi_1_3 * eta_y,
    eta_m ~ phi_2_1 * eta_x + phi_2_2 * eta_m + phi_2_3 * eta_y,
    eta_y ~ phi_3_1 * eta_x + phi_3_2 * eta_m + phi_3_3 * eta_y
  ),
  startval = c(
    phi_1_1 = -0.2, phi_2_1 = 0.0, phi_3_1 = 0.0,
    phi_1_2 = 0.0, phi_2_2 = -0.2, phi_3_2 = 0.0,
    phi_1_3 = 0.0, phi_2_3 = 0.0, phi_3_3 = -0.2
  ),
  isContinuousTime = TRUE
)
```

### Prepare the Noise Matrices


``` r
dynr_noise <- prep.noise(
  values.latent = matrix(
    data = 0.2 * diag(3),
    nrow = 3
  ),
  params.latent = matrix(
    data = c(
      "sigma_1_1", "sigma_2_1", "sigma_3_1",
      "sigma_2_1", "sigma_2_2", "sigma_3_2",
      "sigma_3_1", "sigma_3_2", "sigma_3_3"
    ),
    nrow = 3
  ),
  values.observed = 0.2 * diag(3),
  params.observed = matrix(
    data = c(
      "theta_1_1", "fixed", "fixed",
      "fixed", "theta_2_2", "fixed",
      "fixed", "fixed", "theta_3_3"
    ),
    nrow = 3
  )
)
```

### Prepare the Model

In this example, we increase the maximum evaluations in the optimization process
and constrain the lower and upper bounds of the parameters for the drift matrix.


``` r
dynr_model <- dynr.model(
  data = dynr_data,
  initial = dynr_initial,
  measurement = dynr_measurement,
  dynamics = dynr_dynamics,
  noise = dynr_noise,
  outfile = tempfile(
    paste0(
      "src-",
      format(
        Sys.time(),
        "%Y-%m-%d-%H-%M-%OS3"
      )
    ),
    fileext = ".c"
  )
)
dynr_model@options$maxeval <- 100000
lb <- ub <- rep(NA, times = length(dynr_model$xstart))
names(ub) <- names(lb) <- names(dynr_model$xstart)
lb[
  c(
    "phi_1_1", "phi_2_1", "phi_3_1",
    "phi_1_2", "phi_2_2", "phi_3_2",
    "phi_1_3", "phi_2_3", "phi_3_3"
  )
] <- -1.5
ub[
  c(
    "phi_1_1", "phi_2_1", "phi_3_1",
    "phi_1_2", "phi_2_2", "phi_3_2",
    "phi_1_3", "phi_2_3", "phi_3_3"
  )
] <- 1.5
dynr_model$lb <- lb
dynr_model$ub <- ub
```

### Fit the Model


``` r
fit <- dynr.cook(
  dynr_model,
  verbose = FALSE
)
#> [1] "Get ready!!!!"
#> using C compiler: ‘gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0’
#> Optimization function called.
#> Starting Hessian calculation ...
#> Finished Hessian calculation.
#> Original exit flag:  3 
#> Modified exit flag:  3 
#> Optimization terminated successfully: ftol_rel or ftol_abs was reached. 
#> Original fitted parameters:  -0.2938068 0.8243958 -0.4543161 -0.07191554 
#> -0.5689988 0.707647 0.0257906 0.08266777 -0.6875018 -1.444748 0.07916771 
#> -0.2743246 -2.582169 0.1772108 -2.804538 -1.604288 -1.652135 -1.622277 
#> -0.06854665 0.08457349 0.1157208 -0.05902915 0.1716259 0.1095353 0.379774 
#> -0.08084045 -0.07765934 
#> 
#> Transformed fitted parameters:  -0.2938068 0.8243958 -0.4543161 -0.07191554 
#> -0.5689988 0.707647 0.0257906 0.08266777 -0.6875018 0.2358056 0.01866819 
#> -0.06468727 0.07708775 0.008277734 0.08065449 0.2010327 0.1916402 0.1974485 
#> -0.06854665 0.08457349 0.1157208 0.9426793 0.1617882 0.1032567 1.489721 
#> -0.1004635 0.946144 
#> 
#> Doing end processing
#> Successful trial
#> Total Time: 5.501934 
#> Backend Time: 5.49238
summary(fit)
#> Coefficients:
#>              Estimate Std. Error t value   ci.lower   ci.upper Pr(>|t|)    
#> phi_1_1    -0.2938068  0.0820046  -3.583 -0.4545328 -0.1330807   0.0002 ***
#> phi_2_1     0.8243958  0.0566320  14.557  0.7133991  0.9353925   <2e-16 ***
#> phi_3_1    -0.4543161  0.0574999  -7.901 -0.5670137 -0.3416184   <2e-16 ***
#> phi_1_2    -0.0719155  0.0683123  -1.053 -0.2058053  0.0619742   0.1463    
#> phi_2_2    -0.5689988  0.0482579 -11.791 -0.6635825 -0.4744151   <2e-16 ***
#> phi_3_2     0.7076470  0.0485039  14.589  0.6125811  0.8027128   <2e-16 ***
#> phi_1_3     0.0257906  0.0622339   0.414 -0.0961855  0.1477667   0.3393    
#> phi_2_3     0.0826678  0.0432912   1.910 -0.0021815  0.1675170   0.0281 *  
#> phi_3_3    -0.6875018  0.0439895 -15.629 -0.7737196 -0.6012840   <2e-16 ***
#> sigma_1_1   0.2358056  0.0226976  10.389  0.1913191  0.2802920   <2e-16 ***
#> sigma_2_1   0.0186682  0.0100337   1.861 -0.0009975  0.0383339   0.0314 *  
#> sigma_3_1  -0.0646873  0.0107504  -6.017 -0.0857577 -0.0436168   <2e-16 ***
#> sigma_2_2   0.0770878  0.0094136   8.189  0.0586374  0.0955381   <2e-16 ***
#> sigma_3_2   0.0082777  0.0066195   1.251 -0.0046963  0.0212518   0.1056    
#> sigma_3_3   0.0806545  0.0101752   7.927  0.0607115  0.1005975   <2e-16 ***
#> theta_1_1   0.2010327  0.0051032  39.394  0.1910306  0.2110348   <2e-16 ***
#> theta_2_2   0.1916402  0.0043702  43.851  0.1830748  0.2002057   <2e-16 ***
#> theta_3_3   0.1974485  0.0045195  43.688  0.1885905  0.2063066   <2e-16 ***
#> mu0_1_1    -0.0685466  0.1417041  -0.484 -0.3462816  0.2091883   0.3143    
#> mu0_2_1     0.0845735  0.1744574   0.485 -0.2573568  0.4265038   0.3139    
#> mu0_3_1     0.1157208  0.1405318   0.823 -0.1597166  0.3911581   0.2051    
#> sigma0_1_1  0.9426793  0.2001859   4.709  0.5503221  1.3350365   <2e-16 ***
#> sigma0_2_1  0.1617882  0.1775634   0.911 -0.1862298  0.5098061   0.1811    
#> sigma0_3_1  0.1032567  0.1428290   0.723 -0.1766831  0.3831964   0.2349    
#> sigma0_2_2  1.4897212  0.3064350   4.861  0.8891197  2.0903227   <2e-16 ***
#> sigma0_3_2 -0.1004635  0.1764438  -0.569 -0.4462870  0.2453600   0.2846    
#> sigma0_3_3  0.9461440  0.1974849   4.791  0.5590807  1.3332073   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> -2 log-likelihood value at convergence = 21626.57
#> AIC = 21680.57
#> BIC = 21856.53
coefs <- coef(fit)
vcovs <- vcov(fit)
```

### Extract Matrices from the Fitted Model to use in cTMed


``` r
phi_names <- c(
  "phi_1_1", "phi_2_1", "phi_3_1",
  "phi_1_2", "phi_2_2", "phi_3_2",
  "phi_1_3", "phi_2_3", "phi_3_3"
)
sigma_names <- c(
  "sigma_1_1", "sigma_2_1", "sigma_3_1",
  "sigma_2_1", "sigma_2_2", "sigma_3_2",
  "sigma_3_1", "sigma_3_2", "sigma_3_3"
)
sigma_vech_names <- c(
  "sigma_1_1", "sigma_2_1", "sigma_3_1",
  "sigma_2_2", "sigma_3_2",
  "sigma_3_3"
)
theta_names <- c(
  "phi_1_1", "phi_2_1", "phi_3_1",
  "phi_1_2", "phi_2_2", "phi_3_2",
  "phi_1_3", "phi_2_3", "phi_3_3",
  "sigma_1_1", "sigma_2_1", "sigma_3_1",
  "sigma_2_2", "sigma_3_2",
  "sigma_3_3"
)
phi <- matrix(
  data = coefs[phi_names],
  nrow = 3,
  ncol = 3
)
sigma <- matrix(
  data = coefs[sigma_names],
  nrow = 3,
  ncol = 3
)
theta <- coefs[theta_names]
vcov_phi_vec <- vcovs[phi_names, phi_names]
vcov_sigma_vech <- vcovs[sigma_vech_names, sigma_vech_names]
vcov_theta <- vcovs[theta_names, theta_names]
```

#### Estimated Drift Matrix with Corresponding Sampling Covariance Matrix


``` r
phi
#>            [,1]        [,2]        [,3]
#> [1,] -0.2938068 -0.07191554  0.02579060
#> [2,]  0.8243958 -0.56899879  0.08266777
#> [3,] -0.4543161  0.70764697 -0.68750180
vcov_phi_vec
#>               phi_1_1       phi_2_1       phi_3_1       phi_1_2       phi_2_2
#> phi_1_1  0.0067247510  3.334401e-04 -1.427365e-03 -0.0048315027 -2.781140e-04
#> phi_2_1  0.0003334401  3.207186e-03 -1.160944e-04 -0.0001311767 -2.396379e-03
#> phi_3_1 -0.0014273654 -1.160944e-04  3.306233e-03  0.0009690095  1.058101e-04
#> phi_1_2 -0.0048315027 -1.311767e-04  9.690095e-04  0.0046665764  1.927798e-04
#> phi_2_2 -0.0002781140 -2.396379e-03  1.058101e-04  0.0001927798  2.328822e-03
#> phi_3_2  0.0010271118  3.666341e-05 -2.433612e-03 -0.0009887664 -8.050796e-05
#> phi_1_3  0.0032991598  4.976013e-05 -6.047423e-04 -0.0033768803 -8.739195e-05
#> phi_2_3  0.0002242026  1.667488e-03 -9.890426e-05 -0.0001916267 -1.709053e-03
#> phi_3_3 -0.0007252163 -6.763331e-06  1.676026e-03  0.0007432086  3.057570e-05
#>               phi_3_2       phi_1_3       phi_2_3       phi_3_3
#> phi_1_1  1.027112e-03  3.299160e-03  2.242026e-04 -7.252163e-04
#> phi_2_1  3.666341e-05  4.976013e-05  1.667488e-03 -6.763331e-06
#> phi_3_1 -2.433612e-03 -6.047423e-04 -9.890426e-05  1.676026e-03
#> phi_1_2 -9.887664e-04 -3.376880e-03 -1.916267e-04  7.432086e-04
#> phi_2_2 -8.050796e-05 -8.739195e-05 -1.709053e-03  3.057570e-05
#> phi_3_2  2.352625e-03  6.636184e-04  1.014057e-04 -1.723398e-03
#> phi_1_3  6.636184e-04  3.873052e-03  1.807258e-04 -8.645868e-04
#> phi_2_3  1.014057e-04  1.807258e-04  1.874130e-03 -9.711251e-05
#> phi_3_3 -1.723398e-03 -8.645868e-04 -9.711251e-05  1.935074e-03
```

#### Process Noise Covariance Matrix with Corresponding Sampling Covariance Matrix


``` r
sigma
#>             [,1]        [,2]         [,3]
#> [1,]  0.23580555 0.018668186 -0.064687274
#> [2,]  0.01866819 0.077087751  0.008277734
#> [3,] -0.06468727 0.008277734  0.080654490
vcov_sigma_vech
#>               sigma_1_1     sigma_2_1     sigma_3_1     sigma_2_2     sigma_3_2
#> sigma_1_1  5.151809e-04  1.300951e-05 -9.426519e-05  1.267967e-06 -5.237358e-06
#> sigma_2_1  1.300951e-05  1.006750e-04 -3.297983e-06  4.598455e-06 -2.216763e-05
#> sigma_3_1 -9.426519e-05 -3.297983e-06  1.155716e-04 -4.564779e-07  3.331124e-06
#> sigma_2_2  1.267967e-06  4.598455e-06 -4.564779e-07  8.861586e-05 -2.460733e-06
#> sigma_3_2 -5.237358e-06 -2.216763e-05  3.331124e-06 -2.460733e-06  4.381809e-05
#> sigma_3_3  1.929030e-05  1.521518e-06 -4.733325e-05 -1.238551e-07 -2.475766e-06
#>               sigma_3_3
#> sigma_1_1  1.929030e-05
#> sigma_2_1  1.521518e-06
#> sigma_3_1 -4.733325e-05
#> sigma_2_2 -1.238551e-07
#> sigma_3_2 -2.475766e-06
#> sigma_3_3  1.035347e-04
```

#### Estimated Drift Matrix and Process Noise Covariance Matrix with Corresponding Sampling Covariance Matrix


``` r
theta
#>      phi_1_1      phi_2_1      phi_3_1      phi_1_2      phi_2_2      phi_3_2 
#> -0.293806757  0.824395779 -0.454316070 -0.071915543 -0.568998788  0.707646969 
#>      phi_1_3      phi_2_3      phi_3_3    sigma_1_1    sigma_2_1    sigma_3_1 
#>  0.025790605  0.082667770 -0.687501801  0.235805551  0.018668186 -0.064687274 
#>    sigma_2_2    sigma_3_2    sigma_3_3 
#>  0.077087751  0.008277734  0.080654490
vcov_theta
#>                 phi_1_1       phi_2_1       phi_3_1       phi_1_2       phi_2_2
#> phi_1_1    6.724751e-03  3.334401e-04 -1.427365e-03 -4.831503e-03 -2.781140e-04
#> phi_2_1    3.334401e-04  3.207186e-03 -1.160944e-04 -1.311767e-04 -2.396379e-03
#> phi_3_1   -1.427365e-03 -1.160944e-04  3.306233e-03  9.690095e-04  1.058101e-04
#> phi_1_2   -4.831503e-03 -1.311767e-04  9.690095e-04  4.666576e-03  1.927798e-04
#> phi_2_2   -2.781140e-04 -2.396379e-03  1.058101e-04  1.927798e-04  2.328822e-03
#> phi_3_2    1.027112e-03  3.666341e-05 -2.433612e-03 -9.887664e-04 -8.050796e-05
#> phi_1_3    3.299160e-03  4.976013e-05 -6.047423e-04 -3.376880e-03 -8.739195e-05
#> phi_2_3    2.242026e-04  1.667488e-03 -9.890426e-05 -1.916267e-04 -1.709053e-03
#> phi_3_3   -7.252163e-04 -6.763331e-06  1.676026e-03  7.432086e-04  3.057570e-05
#> sigma_1_1 -1.092537e-03 -1.397793e-04  2.507219e-04  6.151791e-04  8.109672e-05
#> sigma_2_1  9.993127e-05 -2.401283e-04 -3.783337e-05 -1.262283e-04  1.271903e-04
#> sigma_3_1  1.343481e-04  2.923756e-05 -2.733343e-04 -3.607622e-05 -1.029727e-05
#> sigma_2_2 -4.215240e-06  1.126872e-04  1.182182e-05  5.438527e-06 -1.380388e-04
#> sigma_3_2 -4.999399e-06  2.973246e-05  5.315983e-05  1.147415e-05  6.618861e-06
#> sigma_3_3 -2.724559e-05 -1.369809e-05  5.725382e-05  6.594377e-06  5.235267e-06
#>                 phi_3_2       phi_1_3       phi_2_3       phi_3_3     sigma_1_1
#> phi_1_1    1.027112e-03  3.299160e-03  2.242026e-04 -7.252163e-04 -1.092537e-03
#> phi_2_1    3.666341e-05  4.976013e-05  1.667488e-03 -6.763331e-06 -1.397793e-04
#> phi_3_1   -2.433612e-03 -6.047423e-04 -9.890426e-05  1.676026e-03  2.507219e-04
#> phi_1_2   -9.887664e-04 -3.376880e-03 -1.916267e-04  7.432086e-04  6.151791e-04
#> phi_2_2   -8.050796e-05 -8.739195e-05 -1.709053e-03  3.057570e-05  8.109672e-05
#> phi_3_2    2.352625e-03  6.636184e-04  1.014057e-04 -1.723398e-03 -1.428867e-04
#> phi_1_3    6.636184e-04  3.873052e-03  1.807258e-04 -8.645868e-04 -2.886918e-04
#> phi_2_3    1.014057e-04  1.807258e-04  1.874130e-03 -9.711251e-05 -4.114951e-05
#> phi_3_3   -1.723398e-03 -8.645868e-04 -9.711251e-05  1.935074e-03  6.991235e-05
#> sigma_1_1 -1.428867e-04 -2.886918e-04 -4.114951e-05  6.991235e-05  5.151809e-04
#> sigma_2_1  3.918032e-05  7.547975e-05 -5.717899e-05 -2.268938e-05  1.300951e-05
#> sigma_3_1  1.423087e-04 -6.733013e-05 -7.351539e-06 -4.166032e-05 -9.426519e-05
#> sigma_2_2 -1.299085e-05 -2.872326e-06  8.372301e-05  7.965476e-06  1.267967e-06
#> sigma_3_2 -6.380096e-05 -3.960416e-06 -4.347965e-05  3.509239e-05 -5.237358e-06
#> sigma_3_3  1.600695e-05  2.072470e-05  5.891375e-06 -1.016038e-04  1.929030e-05
#>               sigma_2_1     sigma_3_1     sigma_2_2     sigma_3_2     sigma_3_3
#> phi_1_1    9.993127e-05  1.343481e-04 -4.215240e-06 -4.999399e-06 -2.724559e-05
#> phi_2_1   -2.401283e-04  2.923756e-05  1.126872e-04  2.973246e-05 -1.369809e-05
#> phi_3_1   -3.783337e-05 -2.733343e-04  1.182182e-05  5.315983e-05  5.725382e-05
#> phi_1_2   -1.262283e-04 -3.607622e-05  5.438527e-06  1.147415e-05  6.594377e-06
#> phi_2_2    1.271903e-04 -1.029727e-05 -1.380388e-04  6.618861e-06  5.235267e-06
#> phi_3_2    3.918032e-05  1.423087e-04 -1.299085e-05 -6.380096e-05  1.600695e-05
#> phi_1_3    7.547975e-05 -6.733013e-05 -2.872326e-06 -3.960416e-06  2.072470e-05
#> phi_2_3   -5.717899e-05 -7.351539e-06  8.372301e-05 -4.347965e-05  5.891375e-06
#> phi_3_3   -2.268938e-05 -4.166032e-05  7.965476e-06  3.509239e-05 -1.016038e-04
#> sigma_1_1  1.300951e-05 -9.426519e-05  1.267967e-06 -5.237358e-06  1.929030e-05
#> sigma_2_1  1.006750e-04 -3.297983e-06  4.598455e-06 -2.216763e-05  1.521518e-06
#> sigma_3_1 -3.297983e-06  1.155716e-04 -4.564779e-07  3.331124e-06 -4.733325e-05
#> sigma_2_2  4.598455e-06 -4.564779e-07  8.861586e-05 -2.460733e-06 -1.238551e-07
#> sigma_3_2 -2.216763e-05  3.331124e-06 -2.460733e-06  4.381809e-05 -2.475766e-06
#> sigma_3_3  1.521518e-06 -4.733325e-05 -1.238551e-07 -2.475766e-06  1.035347e-04
```

## References


