---
title: "Total, Direct, and Indirect Effects in Continuous-Time Mediation Model (Bootstrap)"
author: Ivan Jacob Agaloos Pesigan
date: "2024-12-26"
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @RCoreTeam-2024
  @Deboeck-Preacher-2015
  @Ryan-Hamaker-2021
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Total, Direct, and Indirect Effects in Continuous-Time Mediation Model (Bootstrap)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



The `cTMed` package provides a bootstrap approach, in addition to the delta and Monte Carlo methods, for estimating and quantifying uncertainty in total, direct, and indirect effects within continuous-time mediation models across different time intervals.





















In this example, we will use the fitted model from [Fit the Continuous-Time Vector Autoregressive Model Using the OpenMx Package](https://jeksterslab.github.io/cTMed/articles/fit-ct-var-mx.html). The object `fit` represents a fitted CT-VAR model created using the `OpenMx` package.


``` r
summary(fit)
#> Summary of CTVAR 
#>  
#> free parameters:
#>         name         matrix   row   col     Estimate   Std.Error A lbound
#> 1     phi_11    CTVAR_1.phi eta_x eta_x -0.293790977 0.082131220     -1.5
#> 2     phi_21    CTVAR_1.phi eta_m eta_x  0.824373597 0.056712190     -1.5
#> 3     phi_31    CTVAR_1.phi eta_y eta_x -0.454352943 0.057712619     -1.5
#> 4     phi_12    CTVAR_1.phi eta_x eta_m -0.071925733 0.068460953     -1.5
#> 5     phi_22    CTVAR_1.phi eta_m eta_m -0.568941561 0.048328345     -1.5
#> 6     phi_32    CTVAR_1.phi eta_y eta_m  0.707694578 0.048682892     -1.5
#> 7     phi_13    CTVAR_1.phi eta_x eta_y  0.025788921 0.062371709     -1.5
#> 8     phi_23    CTVAR_1.phi eta_m eta_y  0.082690319 0.043347036     -1.5
#> 9     phi_33    CTVAR_1.phi eta_y eta_y -0.687497462 0.044106637     -1.5
#> 10  sigma_11  CTVAR_1.sigma eta_x eta_x  0.230160010 0.022629412        0
#> 11  sigma_12  CTVAR_1.sigma eta_x eta_m  0.027993628 0.009999226         
#> 12  sigma_22  CTVAR_1.sigma eta_m eta_m  0.078892245 0.009570698        0
#> 13  sigma_13  CTVAR_1.sigma eta_x eta_y -0.067896170 0.010706785         
#> 14  sigma_23  CTVAR_1.sigma eta_m eta_y  0.004510462 0.006768976         
#> 15  sigma_33  CTVAR_1.sigma eta_y eta_y  0.084365276 0.010385763        0
#> 16  theta_11  CTVAR_1.theta     x     x  0.201040221 0.005103784        0
#> 17  theta_22  CTVAR_1.theta     m     m  0.191651068 0.004371682        0
#> 18  theta_33  CTVAR_1.theta     y     y  0.197460049 0.004520322        0
#> 19     mu0_1    CTVAR_1.mu0 eta_x   mu0 -0.068444306 0.141833181         
#> 20     mu0_2    CTVAR_1.mu0 eta_m   mu0  0.084620005 0.175303157         
#> 21     mu0_3    CTVAR_1.mu0 eta_y   mu0  0.115770249 0.141100567         
#> 22 sigma0_11 CTVAR_1.sigma0 eta_x eta_x  0.942751969 0.202350021        0
#> 23 sigma0_12 CTVAR_1.sigma0 eta_x eta_m  0.161848185 0.178506451         
#> 24 sigma0_22 CTVAR_1.sigma0 eta_m eta_m  1.489764695 0.309416239        0
#> 25 sigma0_13 CTVAR_1.sigma0 eta_x eta_y  0.103298448 0.143255187 !       
#> 26 sigma0_23 CTVAR_1.sigma0 eta_m eta_y -0.100426750 0.177014576 !       
#> 27 sigma0_33 CTVAR_1.sigma0 eta_y eta_y  0.946206282 0.201001057 !      0
#>    ubound
#> 1     1.5
#> 2     1.5
#> 3     1.5
#> 4     1.5
#> 5     1.5
#> 6     1.5
#> 7     1.5
#> 8     1.5
#> 9     1.5
#> 10       
#> 11       
#> 12       
#> 13       
#> 14       
#> 15       
#> 16       
#> 17       
#> 18       
#> 19       
#> 20       
#> 21       
#> 22       
#> 23       
#> 24       
#> 25       
#> 26       
#> 27       
#> 
#> Model Statistics: 
#>                |  Parameters  |  Degrees of Freedom  |  Fit (-2lnL units)
#>        Model:             27                  14973              21626.57
#>    Saturated:             NA                     NA                    NA
#> Independence:             NA                     NA                    NA
#> Number of observations/statistics: 5000/15000
#> 
#> Information Criteria: 
#>       |  df Penalty  |  Parameters Penalty  |  Sample-Size Adjusted
#> AIC:       -8319.43               21680.57                 21680.87
#> BIC:     -105901.36               21856.53                 21770.74
#> CFI: NA 
#> TLI: 1   (also known as NNFI) 
#> RMSEA:  0  [95% CI (NA, NA)]
#> Prob(RMSEA <= 0.05): NA
#> To get additional fit indices, see help(mxRefModels)
#> timestamp: 2024-12-26 04:43:33 
#> Wall clock time: 177.2153 secs 
#> optimizer:  SLSQP 
#> OpenMx version number: 2.21.13 
#> Need help?  See help(mxSummary)
```

We need to extract the estimated parameters from the fitted object, which will be used to generate new data.


``` r
est <- coef(fit)
n <- 50
n
#> [1] 50
time <- 100
time
#> [1] 100
mu0 <- est[
  c(
    "mu0_1",
    "mu0_2",
    "mu0_3"
  )
]
mu0
#>       mu0_1       mu0_2       mu0_3 
#> -0.06844431  0.08462000  0.11577025
sigma0 <- matrix(
  data = est[
    c(
      "sigma0_11",
      "sigma0_12",
      "sigma0_13",
      "sigma0_12",
      "sigma0_22",
      "sigma0_23",
      "sigma0_13",
      "sigma0_23",
      "sigma0_33"
    )
  ],
  nrow = 3,
  ncol = 3
)
sigma0
#>           [,1]       [,2]       [,3]
#> [1,] 0.9427520  0.1618482  0.1032984
#> [2,] 0.1618482  1.4897647 -0.1004268
#> [3,] 0.1032984 -0.1004268  0.9462063
sigma0_l <- t(chol(sigma0))
phi <- matrix(
  data = est[
    c(
      "phi_11",
      "phi_21",
      "phi_31",
      "phi_12",
      "phi_22",
      "phi_32",
      "phi_13",
      "phi_23",
      "phi_33"
    )
  ],
  nrow = 3,
  ncol = 3
)
phi
#>            [,1]        [,2]        [,3]
#> [1,] -0.2937910 -0.07192573  0.02578892
#> [2,]  0.8243736 -0.56894156  0.08269032
#> [3,] -0.4543529  0.70769458 -0.68749746
sigma <- matrix(
  data = est[
    c(
      "sigma_11", "sigma_12", "sigma_13",
      "sigma_12", "sigma_22", "sigma_23",
      "sigma_13", "sigma_23", "sigma_33"
    )
  ],
  nrow = 3,
  ncol = 3
)
sigma
#>             [,1]        [,2]         [,3]
#> [1,]  0.23016001 0.027993628 -0.067896170
#> [2,]  0.02799363 0.078892245  0.004510462
#> [3,] -0.06789617 0.004510462  0.084365276
sigma_l <- t(chol(sigma))
theta <- diag(3)
diag(theta) <- est[
  c(
    "theta_11",
    "theta_22",
    "theta_33"
  )
]
theta
#>           [,1]      [,2]    [,3]
#> [1,] 0.2010402 0.0000000 0.00000
#> [2,] 0.0000000 0.1916511 0.00000
#> [3,] 0.0000000 0.0000000 0.19746
theta_l <- t(chol(theta))
```



The estimated parameters are then passed as arguments to the `BootPara` function, which generates a bootstrap sampling distribution of drift matrices. The resulting object, `phi`, is a list containing the drift matrices. Refer to the code below for details on the `BootPara` function.

> **_NOTE:_**  Fitting the CT-VAR model multiple times is computationally intensive. 


``` r
phi <- BootPara(
  B = 1000L,
  n = n,
  time = time,
  mu0 = mu0,
  sigma0_l = sigma0_l,
  phi = phi,
  sigma_l = sigma_l,
  lambda = lambda,
  theta_l = theta_l,
  ncores = parallel::detectCores(), # use multiple cores
  seed = 42
)
#> Error in get(name, envir = envir): object 'GenDataCTVAR' not found
```

In this example, we aim to calculate the total, direct, and indirect effects of `x` on `y`, mediated through `m`, over time intervals ranging from 0 to 10.


``` r
# time intervals
delta_t <- seq(from = 0, to = 10, length.out = 1000)
```

We also need the estimated drift matrix from the original sample.


``` r
# estimated drift matrix
phi_hat <- matrix(
  data = est[
    c(
      "phi_11",
      "phi_21",
      "phi_31",
      "phi_12",
      "phi_22",
      "phi_32",
      "phi_13",
      "phi_23",
      "phi_33"
    )
  ],
  nrow = 3,
  ncol = 3
)
colnames(phi_hat) <- rownames(phi_hat) <- c("x", "m", "y")
```

## Bootstrap Method


``` r
library(cTMed)
boot <- BootMed(
  phi = phi,
  phi_hat = phi_hat,
  delta_t = delta_t,
  from = "x",
  to = "y",
  med = "m",
  ncores = parallel::detectCores() # use multiple cores
)
#> Error in checkForRemoteErrors(val): 8 nodes produced errors; first error: Not a matrix.
plot(boot)
#> Error: object 'boot' not found
```

<details>
<summary>
Code to generate data and fit the model B number of times.
</summary>
```r
library(simStateSpace)
library(OpenMx)
BootPara <- function(B = 1000L,
                     n,
                     time,
                     mu0,
                     sigma0_l,
                     phi,
                     sigma_l,
                     lambda,
                     theta_l,
                     ncores,
                     seed = 42) {
  mxOption(
    key = "Number of Threads",
    value = 1
  )
  GenDataCTVAR <- function(n,
                           time,
                           mu0,
                           sigma0_l,
                           phi,
                           sigma_l,
                           theta_l) {
    sim <- SimSSMOUFixed(
      n = n,
      time = time,
      delta_t = 0.1,
      mu0 = mu0,
      sigma0_l = sigma0_l,
      mu = c(0, 0, 0),
      phi = phi,
      sigma_l = sigma_l,
      nu = c(0, 0, 0),
      lambda = diag(3),
      theta_l = theta_l,
      type = 0
    )
    data <- as.data.frame(sim)
    colnames(data) <- c("id", "time", "x", "m", "y")
    return(data)
  }
  FitCTVAR <- function(data) {
    mu0 <- mxMatrix(
      type = "Full",
      nrow = 3,
      ncol = 1,
      free = TRUE,
      values = matrix(
        data = c(
          0, 0, 0
        ),
        nrow = 3,
        ncol = 1
      ),
      labels = matrix(
        data = c(
          "mu0_1", "mu0_2", "mu0_3"
        ),
        nrow = 3,
        ncol = 1
      ),
      lbound = NA,
      ubound = NA,
      byrow = FALSE,
      dimnames = list(
        c("eta_x", "eta_m", "eta_y"),
        "mu0"
      ),
      name = "mu0"
    )
    sigma0 <- mxMatrix(
      type = "Symm",
      nrow = 3,
      ncol = 3,
      free = TRUE,
      values = matrix(
        data = c(
          1.0, 0.2, 0.2,
          0.2, 1.0, 0.2,
          0.2, 0.2, 1.0
        ),
        nrow = 3,
        ncol = 3
      ),
      labels = matrix(
        data = c(
          "sigma0_11", "sigma0_12", "sigma0_13",
          "sigma0_12", "sigma0_22", "sigma0_23",
          "sigma0_13", "sigma0_23", "sigma0_33"
        ),
        nrow = 3,
        ncol = 3
      ),
      lbound = matrix(
        data = c(
          0, NA, NA,
          NA, 0, NA,
          NA, NA, 0
        ),
        nrow = 3,
        ncol = 3
      ),
      ubound = NA,
      byrow = FALSE,
      dimnames = list(
        c("eta_x", "eta_m", "eta_y"),
        c("eta_x", "eta_m", "eta_y")
      ),
      name = "sigma0"
    )
    lambda <- mxMatrix(
      type = "Diag",
      nrow = 3,
      ncol = 3,
      free = FALSE,
      values = 1,
      labels = NA,
      lbound = NA,
      ubound = NA,
      byrow = FALSE,
      dimnames = list(
        c("x", "m", "y"),
        c("eta_x", "eta_m", "eta_y")
      ),
      name = "lambda"
    )
    phi <- mxMatrix(
      type = "Full",
      nrow = 3,
      ncol = 3,
      free = TRUE,
      values = matrix(
        data = c(
          -0.2, 0.0, 0.0,
          0.0, -0.2, 0.0,
          0.0, 0.0, -0.2
        ),
        nrow = 3,
        ncol = 3
      ),
      labels = matrix(
        data = c(
          "phi_11", "phi_21", "phi_31",
          "phi_12", "phi_22", "phi_32",
          "phi_13", "phi_23", "phi_33"
        ),
        nrow = 3,
        ncol = 3
      ),
      lbound = -1.5,
      ubound = 1.5,
      byrow = FALSE,
      dimnames = list(
        c("eta_x", "eta_m", "eta_y"),
        c("eta_x", "eta_m", "eta_y")
      ),
      name = "phi"
    )
    sigma <- mxMatrix(
      type = "Symm",
      nrow = 3,
      ncol = 3,
      free = TRUE,
      values = 0.2 * diag(3),
      labels = matrix(
        data = c(
          "sigma_11", "sigma_12", "sigma_13",
          "sigma_12", "sigma_22", "sigma_23",
          "sigma_13", "sigma_23", "sigma_33"
        ),
        nrow = 3,
        ncol = 3
      ),
      lbound = matrix(
        data = c(
          0, NA, NA,
          NA, 0, NA,
          NA, NA, 0
        ),
        nrow = 3,
        ncol = 3
      ),
      ubound = NA,
      byrow = FALSE,
      dimnames = list(
        c("eta_x", "eta_m", "eta_y"),
        c("eta_x", "eta_m", "eta_y")
      ),
      name = "sigma"
    )
    theta <- mxMatrix(
      type = "Diag",
      nrow = 3,
      ncol = 3,
      free = TRUE,
      values = 0.2 * diag(3),
      labels = matrix(
        data = c(
          "theta_11", "fixed", "fixed",
          "fixed", "theta_22", "fixed",
          "fixed", "fixed", "theta_33"
        ),
        nrow = 3,
        ncol = 3
      ),
      lbound = matrix(
        data = c(
          0, NA, NA,
          NA, 0, NA,
          NA, NA, 0
        ),
        nrow = 3,
        ncol = 3
      ),
      ubound = NA,
      byrow = FALSE,
      dimnames = list(
        c("x", "m", "y"),
        c("x", "m", "y")
      ),
      name = "theta"
    )
    time <- mxMatrix(
      type = "Full",
      nrow = 1,
      ncol = 1,
      free = FALSE,
      labels = "data.time",
      name = "time"
    )
    gamma <- mxMatrix(
      type = "Zero",
      nrow = 3,
      ncol = 1,
      name = "gamma"
    )
    kappa <- mxMatrix(
      type = "Zero",
      nrow = 3,
      ncol = 1,
      name = "kappa"
    )
    covariate <- mxMatrix(
      type = "Zero",
      nrow = 1,
      ncol = 1,
      name = "covariate"
    )
    model <- mxModel(
      model = "CTVAR",
      phi,
      gamma,
      lambda,
      kappa,
      sigma,
      theta,
      mu0,
      sigma0,
      covariate,
      time,
      mxExpectationStateSpaceContinuousTime(
        A = "phi",
        B = "gamma",
        C = "lambda",
        D = "kappa",
        Q = "sigma",
        R = "theta",
        x0 = "mu0",
        P0 = "sigma0",
        u = "covariate",
        t = "time",
        dimnames = c("x", "m", "y")
      ),
      mxFitFunctionML(),
      mxData(
        observed = data,
        type = "raw"
      )
    )
    ids <- sort(
      unique(data[, "id"])
    )
    model_id <- lapply(
      X = ids,
      FUN = function(i,
                     data,
                     model) {
        return(
          mxModel(
            name = paste0("CTVAR", "_", i),
            model = model,
            mxData(
              observed = data[
                which(
                  data[, "id"] == i
                ), ,
                drop = FALSE
              ],
              type = "raw"
            )
          )
        )
      },
      data = data,
      model = model
    )
    fit <- mxTryHardctsem(
      model = mxModel(
        name = "CTVAR",
        model_id,
        mxFitFunctionMultigroup(
          paste0(
            "CTVAR",
            "_",
            ids
          )
        )
      ),
      extraTries = 1000
    )
    parnames <- c(
      "phi_11",
      "phi_21",
      "phi_31",
      "phi_12",
      "phi_22",
      "phi_32",
      "phi_13",
      "phi_23",
      "phi_33"
    )
    output <- matrix(
      data = coef(fit)[parnames],
      nrow = 3
    )
    colnames(output) <- rownames(output) <- c("x", "m", "y")
    return(output)
  }
  cl <- parallel::makeCluster(ncores)
  parallel::clusterEvalQ(
    cl,
    library("simStateSpace")
  )
  parallel::clusterEvalQ(
    cl,
    library("OpenMx")
  )
  parallel::clusterExport(
    cl = cl,
    varlist = c(
      "GenDataCTVAR",
      "FitCTVAR"
    )
  )
  on.exit(
    parallel::stopCluster(cl = cl)
  )
  parallel::clusterSetRNGStream(
    cl = cl,
    iseed = seed
  )
  return(
    parallel::parLapply(
      cl = cl,
      X = seq_len(B),
      fun = function(i,
                     n,
                     time,
                     mu0,
                     sigma0_l,
                     phi,
                     sigma_l,
                     theta_l) {
        return(
          FitCTVAR(
            data = GenDataCTVAR(
              n = n,
              time = time,
              mu0 = mu0,
              sigma0_l = sigma0_l,
              phi = phi,
              sigma_l = sigma_l,
              theta_l = theta_l
            )
          )
        )
      },
      n = n,
      time = time,
      mu0 = mu0,
      sigma0_l = sigma0_l,
      phi = phi,
      sigma_l = sigma_l,
      theta_l = theta_l
    )
  )
}
```
</details>

## References


