# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.DirectVec <- function(phi_vec, delta_t, from, to, med) {
    .Call('_cTMed_DirectVec', PACKAGE = 'cTMed', phi_vec, delta_t, from, to, med)
}

.Direct <- function(phi, delta_t, from, to, med) {
    .Call('_cTMed_Direct', PACKAGE = 'cTMed', phi, delta_t, from, to, med)
}

.IndirectCentrals <- function(phi, delta_t) {
    .Call('_cTMed_IndirectCentrals', PACKAGE = 'cTMed', phi, delta_t)
}

.IndirectCentralVec <- function(phi_vec, delta_t) {
    .Call('_cTMed_IndirectCentralVec', PACKAGE = 'cTMed', phi_vec, delta_t)
}

.IndirectCentral <- function(phi, delta_t) {
    .Call('_cTMed_IndirectCentral', PACKAGE = 'cTMed', phi, delta_t)
}

.Indirect <- function(phi, delta_t, from, to, med) {
    .Call('_cTMed_Indirect', PACKAGE = 'cTMed', phi, delta_t, from, to, med)
}

.MCPhiI <- function(phi, vcov_phi_vec_l, test_phi = TRUE) {
    .Call('_cTMed_MCPhiI', PACKAGE = 'cTMed', phi, vcov_phi_vec_l, test_phi)
}

.MCPhi <- function(phi, vcov_phi_vec_l, R, test_phi = TRUE) {
    .Call('_cTMed_MCPhi', PACKAGE = 'cTMed', phi, vcov_phi_vec_l, R, test_phi)
}

.Meds <- function(phi, delta_t, from, to, med) {
    .Call('_cTMed_Meds', PACKAGE = 'cTMed', phi, delta_t, from, to, med)
}

.MedVec <- function(phi_vec, delta_t, from, to, med) {
    .Call('_cTMed_MedVec', PACKAGE = 'cTMed', phi_vec, delta_t, from, to, med)
}

.Med <- function(phi, delta_t, from, to, med) {
    .Call('_cTMed_Med', PACKAGE = 'cTMed', phi, delta_t, from, to, med)
}

.TestPhi <- function(phi) {
    .Call('_cTMed_TestPhi', PACKAGE = 'cTMed', phi)
}

.TestStable <- function(x) {
    .Call('_cTMed_TestStable', PACKAGE = 'cTMed', x)
}

.TotalCentrals <- function(phi, delta_t) {
    .Call('_cTMed_TotalCentrals', PACKAGE = 'cTMed', phi, delta_t)
}

.TotalCentralVec <- function(phi_vec, delta_t) {
    .Call('_cTMed_TotalCentralVec', PACKAGE = 'cTMed', phi_vec, delta_t)
}

.TotalCentral <- function(phi, delta_t) {
    .Call('_cTMed_TotalCentral', PACKAGE = 'cTMed', phi, delta_t)
}

.TotalDeltaT <- function(phi, delta_t) {
    .Call('_cTMed_TotalDeltaT', PACKAGE = 'cTMed', phi, delta_t)
}

.TotalVec <- function(phi_vec, delta_t) {
    .Call('_cTMed_TotalVec', PACKAGE = 'cTMed', phi_vec, delta_t)
}

.Total <- function(phi, delta_t) {
    .Call('_cTMed_Total', PACKAGE = 'cTMed', phi, delta_t)
}

