# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.DirectVec <- function(phi_vec, delta_t, from, to, med) {
  .Call(`_cTMed_DirectVec`, phi_vec, delta_t, from, to, med)
}

.Direct <- function(phi, delta_t, from, to, med) {
  .Call(`_cTMed_Direct`, phi, delta_t, from, to, med)
}

.IndirectCentrals <- function(phi, delta_t) {
  .Call(`_cTMed_IndirectCentrals`, phi, delta_t)
}

.IndirectCentralVec <- function(phi_vec, delta_t) {
  .Call(`_cTMed_IndirectCentralVec`, phi_vec, delta_t)
}

.IndirectCentral <- function(phi, delta_t) {
  .Call(`_cTMed_IndirectCentral`, phi, delta_t)
}

.Indirect <- function(phi, delta_t, from, to, med) {
  .Call(`_cTMed_Indirect`, phi, delta_t, from, to, med)
}

.MCMed <- function(phi, vcov_phi_vec_l, delta_t, from, to, med, R, test_phi = TRUE) {
  .Call(`_cTMed_MCMed`, phi, vcov_phi_vec_l, delta_t, from, to, med, R, test_phi)
}

.MCPhiI <- function(phi, vcov_phi_vec_l, test_phi = TRUE) {
  .Call(`_cTMed_MCPhiI`, phi, vcov_phi_vec_l, test_phi)
}

.MCPhi <- function(phi, vcov_phi_vec_l, R, test_phi = TRUE) {
  .Call(`_cTMed_MCPhi`, phi, vcov_phi_vec_l, R, test_phi)
}

.Meds <- function(phi, delta_t, from, to, med) {
  .Call(`_cTMed_Meds`, phi, delta_t, from, to, med)
}

.MedVec <- function(phi_vec, delta_t, from, to, med) {
  .Call(`_cTMed_MedVec`, phi_vec, delta_t, from, to, med)
}

.Med <- function(phi, delta_t, from, to, med) {
  .Call(`_cTMed_Med`, phi, delta_t, from, to, med)
}

#' Test the Drift Matrix
#'
#' Both have to be true for the function to return `TRUE`.
#'   - Test that the real part of all eigenvalues of \eqn{\boldsymbol{\Phi}}
#'     are less than zero.
#'   - Test that the diagonal values of \eqn{\boldsymbol{\Phi}}
#'     are between 0 to negative inifinity.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param phi Numeric matrix.
#'   The drift matrix (\eqn{\boldsymbol{\Phi}}).
#'
#' @examples
#' phi <- matrix(
#'   data = c(
#'     -0.357, 0.771, -0.450,
#'     0.0, -0.511, 0.729,
#'     0, 0, -0.693
#'   ),
#'   nrow = 3
#' )
#' colnames(phi) <- rownames(phi) <- c("x", "m", "y")
#' TestPhi(phi = phi)
#' phi <- matrix(
#'   data = c(
#'     -6, 5.5, 0, 0,
#'     1.25, -2.5, 5.9, -7.3,
#'     0, 0, -6, 2.5,
#'     5, 0, 0, -6
#'   ),
#'   nrow = 4
#' )
#' colnames(phi) <- rownames(phi) <- paste0("y", 1:4)
#' TestPhi(phi = phi)
#'
#' @family Continuous Time Mediation Functions
#' @keywords cTMed test
#' @export
TestPhi <- function(phi) {
  .Call(`_cTMed_TestPhi`, phi)
}

#' Test Stability
#'
#' The function computes the eigenvalues of the input matrix `x`.
#' It checks if the real part of all eigenvalues is negative.
#' If all eigenvalues have negative real parts,
#' the system is considered stable.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param x Numeric matrix.
#'
#' @examples
#' x <- matrix(
#'   data = c(
#'     -0.357, 0.771, -0.450,
#'     0.0, -0.511, 0.729,
#'     0, 0, -0.693
#'   ),
#'   nrow = 3
#' )
#' TestStable(x)
#' x <- matrix(
#'   data = c(
#'     -6, 5.5, 0, 0,
#'     1.25, -2.5, 5.9, -7.3,
#'     0, 0, -6, 2.5,
#'     5, 0, 0, -6
#'   ),
#'   nrow = 4
#' )
#' TestStable(x)
#'
#' @family Continuous Time Mediation Functions
#' @keywords cTMed test
#' @export
TestStable <- function(x) {
  .Call(`_cTMed_TestStable`, x)
}

.TotalCentrals <- function(phi, delta_t) {
  .Call(`_cTMed_TotalCentrals`, phi, delta_t)
}

.TotalCentralVec <- function(phi_vec, delta_t) {
  .Call(`_cTMed_TotalCentralVec`, phi_vec, delta_t)
}

.TotalCentral <- function(phi, delta_t) {
  .Call(`_cTMed_TotalCentral`, phi, delta_t)
}

.TotalDeltaT <- function(phi, delta_t) {
  .Call(`_cTMed_TotalDeltaT`, phi, delta_t)
}

.TotalVec <- function(phi_vec, delta_t) {
  .Call(`_cTMed_TotalVec`, phi_vec, delta_t)
}

.Total <- function(phi, delta_t) {
  .Call(`_cTMed_Total`, phi, delta_t)
}
