# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.DirectStd <- function(phi, sigma, delta_t, from, to, med) {
    .Call(`_cTMed_DirectStd`, phi, sigma, delta_t, from, to, med)
}

.Direct <- function(phi, delta_t, from, to, med) {
    .Call(`_cTMed_Direct`, phi, delta_t, from, to, med)
}

.IndirectCentrals <- function(phi, delta_t) {
    .Call(`_cTMed_IndirectCentrals`, phi, delta_t)
}

.IndirectCentralVec <- function(phi_vec, delta_t) {
    .Call(`_cTMed_IndirectCentralVec`, phi_vec, delta_t)
}

.IndirectCentral <- function(phi, delta_t) {
    .Call(`_cTMed_IndirectCentral`, phi, delta_t)
}

.IndirectStd <- function(phi, sigma, delta_t, from, to, med) {
    .Call(`_cTMed_IndirectStd`, phi, sigma, delta_t, from, to, med)
}

.Indirect <- function(phi, delta_t, from, to, med) {
    .Call(`_cTMed_Indirect`, phi, delta_t, from, to, med)
}

.MCPhiI <- function(phi, vcov_phi_vec_l, test_phi = TRUE) {
    .Call(`_cTMed_MCPhiI`, phi, vcov_phi_vec_l, test_phi)
}

.MCPhiSigmaI <- function(phi, vcov_phi_vec, sigma, vcov_sigma_vech, test_phi = TRUE) {
    .Call(`_cTMed_MCPhiSigmaI`, phi, vcov_phi_vec, sigma, vcov_sigma_vech, test_phi)
}

.MCPhiVecI <- function(phi, vcov_phi_vec_l, test_phi = TRUE) {
    .Call(`_cTMed_MCPhiVecI`, phi, vcov_phi_vec_l, test_phi)
}

.MCPhiVec <- function(phi, vcov_phi_vec_l, R, test_phi = TRUE) {
    .Call(`_cTMed_MCPhiVec`, phi, vcov_phi_vec_l, R, test_phi)
}

.MCPhi <- function(phi, vcov_phi_vec_l, R, test_phi = TRUE) {
    .Call(`_cTMed_MCPhi`, phi, vcov_phi_vec_l, R, test_phi)
}

.Meds <- function(phi, delta_t, from, to, med) {
    .Call(`_cTMed_Meds`, phi, delta_t, from, to, med)
}

.MedStds <- function(phi, sigma, delta_t, from, to, med) {
    .Call(`_cTMed_MedStds`, phi, sigma, delta_t, from, to, med)
}

.MedStdVec <- function(v, delta_t, from, to, med) {
    .Call(`_cTMed_MedStdVec`, v, delta_t, from, to, med)
}

.MedStd <- function(phi, sigma, delta_t, from, to, med) {
    .Call(`_cTMed_MedStd`, phi, sigma, delta_t, from, to, med)
}

.MedVec <- function(phi_vec, delta_t, from, to, med) {
    .Call(`_cTMed_MedVec`, phi_vec, delta_t, from, to, med)
}

.Med <- function(phi, delta_t, from, to, med) {
    .Call(`_cTMed_Med`, phi, delta_t, from, to, med)
}

.TestPhi <- function(phi) {
    .Call(`_cTMed_TestPhi`, phi)
}

.TestStable <- function(x) {
    .Call(`_cTMed_TestStable`, x)
}

.TotalCentrals <- function(phi, delta_t) {
    .Call(`_cTMed_TotalCentrals`, phi, delta_t)
}

.TotalCentralVec <- function(phi_vec, delta_t) {
    .Call(`_cTMed_TotalCentralVec`, phi_vec, delta_t)
}

.TotalCentral <- function(phi, delta_t) {
    .Call(`_cTMed_TotalCentral`, phi, delta_t)
}

.TotalCov <- function(phi, sigma, delta_t) {
    .Call(`_cTMed_TotalCov`, phi, sigma, delta_t)
}

.TotalDeltaT <- function(phi, delta_t) {
    .Call(`_cTMed_TotalDeltaT`, phi, delta_t)
}

.TotalStdDeltaT <- function(phi, sigma, delta_t) {
    .Call(`_cTMed_TotalStdDeltaT`, phi, sigma, delta_t)
}

.TotalStdVec <- function(v, delta_t) {
    .Call(`_cTMed_TotalStdVec`, v, delta_t)
}

.TotalStd <- function(phi, sigma, delta_t) {
    .Call(`_cTMed_TotalStd`, phi, sigma, delta_t)
}

.TotalVec <- function(phi_vec, delta_t) {
    .Call(`_cTMed_TotalVec`, phi_vec, delta_t)
}

.Total <- function(phi, delta_t) {
    .Call(`_cTMed_Total`, phi, delta_t)
}

